@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMjM0NDA4MCwiZXhwIjoxNzIyMzU0ODgwLCJpYXQiOjE3MjIzNDQwODAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.A3gcroGckD_AVORJFCIpkNj4NmG9qeRaBFzkrcACLNM




GET {{API_Shop_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{authToken}}
###

GET {{API_Shop_HostAddress}}/user/2
Accept: application/json
Authorization: Bearer {{authToken}}
###

GET {{API_Shop_HostAddress}}/users/user
Authorization: Bearer {{authToken}}
###

PUT {{API_Shop_HostAddress}}/user/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"upp@mail.fr",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"upp"
}
###

PUT {{API_Shop_HostAddress}}/user/pseudo/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "pseudo":"tadam"
}
###
PUT {{API_Shop_HostAddress}}/user/mail/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"upp@mail.be"
}
###
PUT {{API_Shop_HostAddress}}/user/pwd/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mdp":"Tadam123*",
  "mdpConfirm":"Tadam123*"
}
###
DELETE {{API_Shop_HostAddress}}/user/2
Authorization: Bearer {{authToken}}
###


POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"lily@mail.fr",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"lily"
}
###
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"fake@mail.fr",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"fake"
}
