@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMjQzMDM2MiwiZXhwIjoxNzIyNDQxMTYyLCJpYXQiOjE3MjI0MzAzNjIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.It5ngX06-Pf3GRR8eHgdJzPd3IpxVvck4h3wJIFZb7s




# Allowed
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"lily@mail.fr",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"lily"
}
###


# Admin & User
GET {{API_Shop_HostAddress}}/user/profil
Accept: application/json
Authorization: Bearer {{authToken}}
###


# Admin
GET {{API_Shop_HostAddress}}/user
Accept: application/json
Authorization: Bearer {{authToken}}
###

# Admin
GET {{API_Shop_HostAddress}}/user/2
Accept: application/json
Authorization: Bearer {{authToken}}
###

# Admin
PUT {{API_Shop_HostAddress}}/user/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"user@mail.fr",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"upp"
}
###

# Admin
PUT {{API_Shop_HostAddress}}/user/pseudo/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "pseudo":"tadam"
}
###

# Admin
PUT {{API_Shop_HostAddress}}/user/mail/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"upp@mail.be"
}
###

# Admin
PUT {{API_Shop_HostAddress}}/user/pwd/2
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mdp":"Tadam123*",
  "mdpConfirm":"Tadam123*"
}
###

# Admin
DELETE {{API_Shop_HostAddress}}/user/2
Authorization: Bearer {{authToken}}
###


# User
PUT {{API_Shop_HostAddress}}/user
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"user2@mail.be",
  "mdp":"Test1234*",
  "mdpConfirm":"Test1234*",
  "pseudo":"upp"
}
###

# User
PUT {{API_Shop_HostAddress}}/user/pseudo
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "pseudo":"tadam"
}
###

# User
PUT {{API_Shop_HostAddress}}/user/mail
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mail":"upp@mail.be"
}
###

# User
PUT {{API_Shop_HostAddress}}/user/pwd
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "mdp":"Tadam123*",
  "mdpConfirm":"Tadam123*"
}
###
