@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMjM2NTgwOCwiZXhwIjoxNzIyMzc2NjA4LCJpYXQiOjE3MjIzNjU4MDgsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.707aFBYlr31Eay0FFlvmgSxToDa1VmAuWHoGA4PuzGs


# Admin only
GET {{API_Shop_HostAddress}}/address
Authorization: Bearer {{authToken}}
###


# For admin you need to pass id for target address
PUT {{API_Shop_HostAddress}}/address/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
"PostalCode":"5050",
"StreetNumber":"007",
"StreetName":"toudoum toudoum",
"Country":"France",
"City":"Bip"
}
###


# Role User is required
# No need to pass the ID here,
# the ID is retrieved by the authentication token
PUT {{API_Shop_HostAddress}}/address
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
"PostalCode":"5050",
"StreetNumber":"007",
"StreetName":"toudoum toudoum",
"Country":"France",
"City":"Bip"
}
###


# Admin only
DELETE {{API_Shop_HostAddress}}/address/1
Authorization: Bearer {{authToken}}
###


# Admin only
GET {{API_Shop_HostAddress}}/address/postalCode/5670
Authorization: Bearer {{authToken}}
###


# Admin only
GET {{API_Shop_HostAddress}}/address/city/Nismes
Authorization: Bearer {{authToken}}
###


# Admin only
GET {{API_Shop_HostAddress}}/address/country/Belgique
Authorization: Bearer {{authToken}}
###
