@API_Shop_HostAddress = https://localhost:7054

# Admin
GET {{API_Shop_HostAddress}}/log
Content-Type: application/json
{
"Mail":"admin@mail.be",
"Mdp":"Test1234*"
}
###


# User
 GET {{API_Shop_HostAddress}}/log
Content-Type: application/json
{
"Mail":"user@mail.be",
"Mdp":"Tadam123*"
} 