@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMjM2NTgwOCwiZXhwIjoxNzIyMzc2NjA4LCJpYXQiOjE3MjIzNjU4MDgsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.707aFBYlr31Eay0FFlvmgSxToDa1VmAuWHoGA4PuzGs



# Allowed
GET {{API_Shop_HostAddress}}/article
###

# Allowed
GET {{API_Shop_HostAddress}}/article/frais
###

# Allowed
GET {{API_Shop_HostAddress}}/article/9
###


# Admin only
POST {{API_Shop_HostAddress}}/article
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name":"coca",
  "stock":10,
  "promo":false,
  "price":2.00,
  "categories":[1,2]
}
###

# Admin only
PUT {{API_Shop_HostAddress}}/article/8
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name":"Thon update",
  "stock":5,
  "promo":true,
  "price":2.05,
  "categories":[1,2]
}
###

# Admin only
PUT {{API_Shop_HostAddress}}/article/name/9
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name":"Sprite"
}
###

# Admin only
PUT {{API_Shop_HostAddress}}/article/price/9
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "price":1.50
}
###

# Admin only
PUT {{API_Shop_HostAddress}}/article/promo/9
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "promo":true
}
###

# Admin only
PUT {{API_Shop_HostAddress}}/article/stock/9
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "stock":10000000
}
###

# Admin only
DELETE {{API_Shop_HostAddress}}/article/8
Authorization: Bearer {{authToken}}
###