@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMjI1MzM1NiwiZXhwIjoxNzIyMjY0MTU2LCJpYXQiOjE3MjIyNTMzNTYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.eJTwSqxDTJEopgd-XCLD_Ynq9pij8_fXPJksVJLZC38


# Admin only
POST {{API_Shop_HostAddress}}/category
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name":"super caté"
}
###

# Admin only
GET {{API_Shop_HostAddress}}/category
Accept: application/json
Authorization: Bearer {{authToken}}
###


# Admin only
GET {{API_Shop_HostAddress}}/category/10
Accept: application/json
Authorization: Bearer {{authToken}}
###

# Admin only
PUT {{API_Shop_HostAddress}}/category/10
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name":"super caté update"
}
###

# Admin only
DELETE {{API_Shop_HostAddress}}/category/10
Accept: application/json
Authorization: Bearer {{authToken}}
###