@API_Shop_HostAddress = https://localhost:7054
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJhZG1pbkBtYWlsLmJlIiwidW5pcXVlX25hbWUiOiJ1c2VyMSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcyMTg1NDUxNiwiZXhwIjoxNzIxODY1MzE2LCJpYXQiOjE3MjE4NTQ1MTYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNTQiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAifQ.hK00sI6tEHf9ubWN00wGYJ8dauOfcUkHj6ZsKuOzeWw

GET {{API_Shop_HostAddress}}/address

###

POST {{API_Shop_HostAddress}}/address
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
"PostalCode":"5670",
"StreetNumber":"07",
"StreetName":"toudoum toudoum",
"Country":"France",
"City":"Couvin"
}
###

PUT {{API_Shop_HostAddress}}/address/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
"Country":"Test"
}
###

DELETE {{API_Shop_HostAddress}}/address/1
Authorization: Bearer {{authToken}}

###

GET {{API_Shop_HostAddress}}/address/5670
Authorization: Bearer {{authToken}}

###

GET {{API_Shop_HostAddress}}/address/city/Nismes
Authorization: Bearer {{authToken}}

###

GET {{API_Shop_HostAddress}}/address/country/Belgique
Authorization: Bearer {{authToken}}

###
