@API_Shop_HostAddress = https://localhost:7054

GET {{API_Shop_HostAddress}}/address

###

POST {{API_Shop_HostAddress}}/address
Content-Type: application/json
{
"PostalCode":"5670",
"StreetNumber":"07",
"Country":"France",
"City":"Couvin"
}
###

PUT {{API_Shop_HostAddress}}/address/1
Content-Type: application/json
{
"Country":"Test"
}
###

DELETE {{API_Shop_HostAddress}}/address/1

###

GET {{API_Shop_HostAddress}}/address/5670

###

GET {{API_Shop_HostAddress}}/address/city/Couvin

###

GET {{API_Shop_HostAddress}}/address/country/Belgique

###
