@API_Shop_HostAddress = https://localhost:7054

GET {{API_Shop_HostAddress}}/users
Accept: application/json
###

GET {{API_Shop_HostAddress}}/user/2
###

GET {{API_Shop_HostAddress}}/users/john
###

PUT {{API_Shop_HostAddress}}/user/2
Content-Type  : application/json
{
    "mdp":"update",
    "pseudo":"tesfft"
}
###
DELETE {{API_Shop_HostAddress}}/user/1






###
# POST MOCKUP USER
###
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"john@mail.be",
  "mdp" :"Test1234*",
  "pseudo":"john"
}
###
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"jane@mail.be",
  "mdp" :"Test1234*",
  "pseudo":"jane"
}
###
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"marcel@mail.be",
  "mdp" :"Test1234*",
  "pseudo":"marcel"
}
###
POST {{API_Shop_HostAddress}}/user
Content-Type: application/json
{
  "mail":"victoire@mail.be",
  "mdp" :"Test1234*",
  "pseudo":"victoire"
}
###
# END POST MOCKUP USER
###
